collection_name: agent
persist_directory: chroma_db
k: 3
retrieval_k: 20
distance_threshold: 1.5
data_path: data
md5_hex_store: md5.text
allow_knowledge_file_type: ["txt","pdf"]
chunk_size: 1200
chunk_overlap: 120
separators: ["\n\n","\n","。","！","？","；","，"," ",""]